name: Nightly Build
permissions:
  contents: write
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: make
        run: make -B
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'update data'
